[package]
name = "std140"
version = "0.2.5"
authors = ["Roland Schermer <roland0507@gmail.com>", "zen-chromeless-platform"]
description = "std140 fork"
edition = "2021"
license = "MIT"
readme = "../README.md"

[dependencies]
std140_macros = { path = "../std140_macros" }
