[package]
name = "std140_test"
version = "0.1.0-0.1.0-fork"
authors = ["Roland Schermer <roland0507@gmail.com>", "zen-chromeless-platform"]
edition = "2021"
publish = false
license = "MIT"

[dev-dependencies]
compiletest_rs = "=0.9.0"
std140 = { path = "../std140" }
